
const layerConfigurations = [
    {
      growEditionSizeTo: 50,
      layersOrder: [
        { name: "ArtBoard" },
        { name: "Background" },
        { name: "Helmets" },
        { name: "Hairs" },
        // { name: "Eyeball" },
        // { name: "Eye color" },
        // { name: "Iris" },
        // { name: "Shine" },
        // { name: "Bottom lid" },
        // { name: "Top lid" },
      ],
    },
]    